### PR TITLE
Office365:Bug - Test Connectivity Change

### PR DESCRIPTION
**Pull request by iciubotarasu**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [X] Testing of all the changes has been performed (for bug fixes / features)
- [X] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [X] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [X] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [X] Verify all checks are passing.
- [X] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [X] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
- This change will allow users to test the connectivity without having to re-authenticate each time when using Azure (interactive), but only when changes are done (like client id, or token expired). Also, the asset will appear as healthy in the Asset Health widget.

## What is the current behavior? (OPTIONAL)
- Every time the Test connectivity button is pushed, you are asked to authenticate. Also the Asset Health widget shows the office365 asset as unhealthy.

## What is the new behavior? (OPTIONAL)
- 

## Other information (OPTIONAL)
- 

## Pay close attention to (OPTIONAL)
-

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by ishans-crest** [comment]
Hi @iciubotarasu ,
Could you please let us know why you have changed the code for test connectivity while using the authentication mechanism as Azure Interactive. Are there any bugs fixed by the changes?

**Comment by iciubotarasu** [comment]
> Hi @iciubotarasu , Could you please let us know why you have changed the code for test connectivity while using the authentication mechanism as Azure Interactive. Are there any bugs fixed by the changes?

Every time the Test connectivity button is pushed, you are asked to authenticate. Also the Asset Health widget shows the office365 asset as unhealthy. What I've changed fixes this behavior. I've tested it on my prod environment.

**Comment by ishans-crest** [comment]
Hi @iciubotarasu, 
A phantom health check will show unhealthy status when we have asset with any interactive flow (Azure interactive in our case). As a result of the changes done in this PR, even after selecting the Azure interactive as Auth Type, the flow will only be interactive for the first time, and for the rest of the time it will generate tokens from refresh token. This would create an impression that your auth type parameter is not getting honored. Hence, the actual workflow should be that when interactive is selected as auth type, it should require manual intervention.

**Comment by ishans-crest** [comment]
Could you please provide your views on https://github.com/splunk-soar-connectors/office365/pull/39#issuecomment-1422604125.

**Pull request closed without merging**
